### ISSUE TITLE
Not able to set aws s3 as storage instead local filesystem in alfresco. Model tracking failed

### ISSUE THREAD

**Issue by melani016** [rmberg/alfresco-s3-adapter#5]
1. jdk 11.0.1 & apache maven 3.6.3, installed alfresco using alfresco-content-services-community-full-installer-6.0.2.1-ea-win-x64.exe in windows.
2. i downloaded https://github.com/rmberg/alfresco-s3-adapter/tree/634b50288000aea73299d9e875c8ec66a5305ef7
3. run "mvn clean install" to get amp file
4. copy amp file from target/ to C:\alfresco-content-services-community-full\amps\
5. stop alfresco(tomcat & postgres) and install the amp file using mmt tool
java -jar /c/alfresco-content-services-community-full/bin/alfresco-mmt.jar install /c/alfresco-content-services-community-full/amps/alfresco-cloud-store.amp C:/alfresco-content-services-community-full/tomcat/webapps/alfresco.war -verbose -force -nobackup
6. using below command, checked if module installed successfully
java -jar /c/alfresco-content-services-community-full/bin/alfresco-mmt.jar list C:/alfresco-content-services-community-full/tomcat/webapps/alfresco.war
7. After restarting alfresco, getting these errors- Model tracking failed
2021-02-11 13:12:16 Commons Daemon procrun stdout initialized
2021-02-11 13:12:29,719 INFO [config.packaging.ModulePackageManager] [localhost-startStop-1] Found 1 module package(s)
2021-02-11 13:12:29,720 INFO [config.packaging.ModulePackageManager] [localhost-startStop-1] Alfresco / Google Docs Share Module, 3.0.4.2, The Share side artifacts of the Alfresco / Google Docs Integration.
2021-02-11 13:12:30,161 INFO [extensions.webscripts.TemplateProcessorRegistry] [localhost-startStop-1] Registered template processor freemarker for extension ftl
2021-02-11 13:12:30,164 INFO [extensions.webscripts.ScriptProcessorRegistry] [localhost-startStop-1] Registered script processor javascript for extension js
2021-02-11 13:12:30,165 INFO [extensions.webscripts.TemplateProcessorRegistry] [localhost-startStop-1] Registered template processor freemarker for extension ftl
2021-02-11 13:12:30,177 INFO [extensions.webscripts.ScriptProcessorRegistry] [localhost-startStop-1] Registered script processor javascript for extension js
2021-02-11 13:12:35,921 INFO [extensions.webscripts.DeclarativeRegistry] [localhost-startStop-1] Registered 393 Web Scripts (+0 failed), 411 URLs
2021-02-11 13:12:35,921 INFO [extensions.webscripts.DeclarativeRegistry] [localhost-startStop-1] Registered 8 Package Description Documents (+0 failed)
2021-02-11 13:12:35,921 INFO [extensions.webscripts.DeclarativeRegistry] [localhost-startStop-1] Registered 0 Schema Description Documents (+0 failed)
2021-02-11 13:12:36,004 INFO [extensions.webscripts.AbstractRuntimeContainer] [localhost-startStop-1] Initialised Surf Container Web Script Container (in 5805.6987ms)
2021-02-11 13:12:36,007 INFO [extensions.webscripts.TemplateProcessorRegistry] [localhost-startStop-1] Registered template processor freemarker for extension ftl
2021-02-11 13:12:36,007 INFO [extensions.webscripts.ScriptProcessorRegistry] [localhost-startStop-1] Registered script processor javascript for extension js
2021-02-11 13:12:47,761 INFO [solr.component.AsyncBuildSuggestComponent] [coreLoadExecutor-5-thread-2] Initializing SuggestComponent
2021-02-11 13:12:47,761 INFO [solr.component.AsyncBuildSuggestComponent] [coreLoadExecutor-5-thread-1] Initializing SuggestComponent
2021-02-11 13:12:47,959 INFO [solr.component.AsyncBuildSuggestComponent] [Suggestor-alfresco-1] Loading suggester index for: shingleBasedSuggestions
2021-02-11 13:12:48,475 INFO [solr.component.AsyncBuildSuggestComponent] [Suggestor-alfresco-1] Loaded suggester shingleBasedSuggestions, took 515 ms
2021-02-11 13:13:01,352 ERROR [solr.tracker.AbstractTracker] [org.alfresco.solr.AlfrescoCoreAdminHandler@34138be4_Worker-1] Model tracking failed
org.alfresco.error.AlfrescoRuntimeException: 01110000 archive GetModelsDiff return status is 404
at org.alfresco.solr.client.SOLRAPIClient.getModelsDiff(SOLRAPIClient.java:1181)
at org.alfresco.solr.tracker.ModelTracker.trackModelsImpl(ModelTracker.java:248)
at org.alfresco.solr.tracker.ModelTracker.trackModels(ModelTracker.java:206)
at org.alfresco.solr.tracker.ModelTracker.ensureFirstModelSync(ModelTracker.java:228)
at org.alfresco.solr.tracker.CoreWatcherJob.registerForCore(CoreWatcherJob.java:145)
at org.alfresco.solr.tracker.CoreWatcherJob.execute(CoreWatcherJob.java:82)
at org.quartz.core.JobRunShell.run(JobRunShell.java:216)
at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:563)
2021-02-11 13:13:01,468 ERROR [solr.tracker.AbstractTracker] [org.alfresco.solr.AlfrescoCoreAdminHandler@34138be4_Worker-1] Model tracking failed
org.alfresco.error.AlfrescoRuntimeException: 01110001 archive GetModelsDiff return status is 404
at org.alfresco.solr.client.SOLRAPIClient.getModelsDiff(SOLRAPIClient.java:1181)
at org.alfresco.solr.tracker.ModelTracker.trackModelsImpl(ModelTracker.java:248)
at org.alfresco.solr.tracker.ModelTracker.trackModels(ModelTracker.java:206)
at org.alfresco.solr.tracker.ModelTracker.ensureFirstModelSync(ModelTracker.java:228)
at org.alfresco.solr.tracker.CoreWatcherJob.registerForCore(CoreWatcherJob.java:145)
at org.alfresco.solr.tracker.CoreWatcherJob.execute(CoreWatcherJob.java:82)
at org.quartz.core.JobRunShell.run(JobRunShell.java:216)
at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:563)
2021-02-11 13:13:15,132 ERROR [solr.tracker.AbstractTracker] [org.alfresco.solr.AlfrescoCoreAdminHandler@34138be4_Worker-4] Tracking failed
org.alfresco.error.AlfrescoRuntimeException: 01110003 api/solr/aclchangesets return status:404
at org.alfresco.solr.client.SOLRAPIClient.getAclChangeSets(SOLRAPIClient.java:169)
at org.alfresco.solr.tracker.AclTracker.checkRepoAndIndexConsistency(AclTracker.java:346)
at org.alfresco.solr.tracker.AclTracker.trackRepository(AclTracker.java:312)
at org.alfresco.solr.tracker.AclTracker.doTrack(AclTracker.java:103)
at org.alfresco.solr.tracker.AbstractTracker.track(AbstractTracker.java:179)
at org.alfresco.solr.tracker.TrackerJob.execute(TrackerJob.java:54)
at org.quartz.core.JobRunShell.run(JobRunShell.java:216)
at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:563)
2021-02-11 13:13:15,134 ERROR [solr.tracker.AbstractTracker] [org.alfresco.solr.AlfrescoCoreAdminHandler@34138be4_Worker-6] Model tracking failed
org.alfresco.error.AlfrescoRuntimeException: 01110005 archive GetModelsDiff return status is 404
at org.alfresco.solr.client.SOLRAPIClient.getModelsDiff(SOLRAPIClient.java:1181)
at org.alfresco.solr.tracker.ModelTracker.trackModelsImpl(ModelTracker.java:248)
at org.alfresco.solr.tracker.ModelTracker.trackModels(ModelTracker.java:206)
at org.alfresco.solr.tracker.ModelTracker.ensureFirstModelSync(ModelTracker.java:228)
at org.alfresco.solr.component.EnsureModelsComponent.prepare(EnsureModelsComponent.java:87)
at org.apache.solr.handler.component.AlfrescoSearchHandler.handleRequestBody(AlfrescoSearchHandler.java:292)
at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:135)
at org.alfresco.solr.Cloud.getResponse(Cloud.java:165)
at org.alfresco.solr.Cloud.getSolrDocumentList(Cloud.java:149)
at org.alfresco.solr.SolrInformationServer.getDocsWithUncleanContent(SolrInformationServer.java:722)
at org.alfresco.solr.tracker.ContentTracker.doTrack(ContentTracker.java:76)
at org.alfresco.solr.tracker.AbstractTracker.track(AbstractTracker.java:179)
at org.alfresco.solr.tracker.TrackerJob.execute(TrackerJob.java:54)
at org.quartz.core.JobRunShell.run(JobRunShell.java:216)
at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:563)

**Comment by melani016** [comment]
in thiscode, https://github.com/rmberg/alfresco-s3-adapter/tree/634b50288000aea73299d9e875c8ec66a5305ef7 and apart from above procedure i changed versions to latest in pom.xml then it worked.
alfresco-sdk-parent --> 2.2.0
